import type { Metadata } from "next";
import { Clock3, Mail, MapPin, Phone } from "lucide-react";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { getSettings } from "@/lib/content";
import { ContactForm } from "@/components/contact/ContactForm";
import { ContentMissing } from "@/components/shared/ContentMissing";
import type { Locale } from "@/types/content";

export const metadata: Metadata = { title: "Contact", description: "Visit 7mmcoffee or send us a message." };
export default async function ContactPage({ params }: { params: Promise<{ locale: string }> }) { const { locale: rawLocale } = await params; const locale = rawLocale as Locale; setRequestLocale(locale); const [settings, t, common] = await Promise.all([getSettings(locale), getTranslations("Contact"), getTranslations("Common")]); if (!settings) return <ContentMissing />; return <section className="px-5 pb-20 pt-36 lg:px-8 lg:pb-28"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-coffee">{t("eyebrow")}</p><h1 className="mt-4 max-w-2xl font-display text-5xl leading-[1.02] text-espresso sm:text-7xl">{t("title")}</h1><div className="mt-14 grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div className="space-y-8"><Info icon={<MapPin />} label={common("location")}>{settings.address}</Info><Info icon={<Phone />} label="Phone"><a href={`tel:${settings.phone}`} className="hover:text-coffee">{settings.phone}</a></Info><Info icon={<Mail />} label="Email"><a href={`mailto:${settings.email}`} className="hover:text-coffee">{settings.email}</a></Info><Info icon={<Clock3 />} label={common("openingHours")}>{settings.openingHours}</Info>{settings.googleMapsUrl && <a href={settings.googleMapsUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-full border border-espresso/25 px-5 text-sm font-medium text-espresso hover:bg-espresso hover:text-white">{t("map")}</a>}</div><ContactForm /></div></div></section>; }
function Info({ icon, label, children }: { icon: React.ReactNode; label: string; children: React.ReactNode }) { return <div className="flex gap-4"><span className="mt-0.5 text-coffee">{icon}</span><div><p className="text-xs font-semibold uppercase tracking-[.17em] text-muted-foreground">{label}</p><div className="mt-2 whitespace-pre-line text-sm leading-6 text-espresso">{children}</div></div></div>; }
