import "dotenv/config";
import bcrypt from "bcryptjs";
import mongoose from "mongoose";
import { connectToDatabase } from "../src/lib/db";
import { About } from "../src/models/About";
import { Category } from "../src/models/Category";
import { Product } from "../src/models/Product";
import { SiteSettings } from "../src/models/SiteSettings";
import { Story } from "../src/models/Story";
import { User } from "../src/models/User";

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=85`;

async function seed() {
  if (!process.env.MONGODB_URI) throw new Error("MONGODB_URI is required before seeding.");
  await connectToDatabase();
  const email = (process.env.SEED_ADMIN_EMAIL || "admin@7mmcoffee.vn").toLowerCase();
  const password = process.env.SEED_ADMIN_PASSWORD || "ChangeMe123!";
  const passwordHash = await bcrypt.hash(password, 12);
  await User.updateOne({ email }, { $set: { name: "7mmcoffee Admin", email, passwordHash, role: "admin" } }, { upsert: true });

  const categories = [
    { nameVi: "Cà phê", nameEn: "Coffee", slug: "coffee", descriptionVi: "Cà phê pha kỹ mỗi ngày.", descriptionEn: "Carefully brewed coffee, every day.", image: image("photo-1447933601403-0c6688de566e"), active: true, displayOrder: 1 },
    { nameVi: "Trà", nameEn: "Tea", slug: "tea", descriptionVi: "Những tách trà thanh mát.", descriptionEn: "Bright, refreshing tea.", image: image("photo-1556679343-c7306c1976bc"), active: true, displayOrder: 2 },
    { nameVi: "Signature", nameEn: "Signature", slug: "signature", descriptionVi: "Những món chỉ có ở 7mmcoffee.", descriptionEn: "Only at 7mmcoffee.", image: image("photo-1495474472287-4d71bcdd2085"), active: true, displayOrder: 3 },
    { nameVi: "Không cà phê", nameEn: "Non-coffee", slug: "non-coffee", descriptionVi: "Êm dịu và đầy năng lượng.", descriptionEn: "Soft, comforting and uplifting.", image: image("photo-1572490122747-3968b75cc699"), active: true, displayOrder: 4 },
    { nameVi: "Bánh ngọt", nameEn: "Pastry", slug: "pastry", descriptionVi: "Bánh nướng tươi cho những buổi chậm rãi.", descriptionEn: "Fresh pastries for slow mornings.", image: image("photo-1509440159596-0249088772ff"), active: true, displayOrder: 5 }
  ];
  for (const category of categories) await Category.updateOne({ slug: category.slug }, { $set: category }, { upsert: true });
  const rows = await Category.find().lean();
  const categoryIds = new Map(rows.map((row) => [row.slug, row._id]));
  const categoryId = (slug: string) => { const id = categoryIds.get(slug); if (!id) throw new Error(`Category ${slug} missing`); return id; };
  const products = [
    ["cold-brew-oat", "Cold Brew Oat", "Cold Brew Oat", "Cold brew ủ chậm 18 giờ, thêm lớp sữa yến mạch mềm mượt.", "18-hour cold brew finished with silky oat milk.", 59000, "coffee", "photo-1517701550927-30cf4ba1dba5", true],
    ["black-on-ice", "Black On Ice", "Black On Ice", "Cà phê đen mạnh mẽ, sáng rõ và mát lạnh.", "Bright, bold black coffee served over ice.", 45000, "coffee", "photo-1494314671902-399b18174975", false],
    ["flat-white", "Flat White", "Flat White", "Espresso cân bằng cùng microfoam mịn như nhung.", "Balanced espresso with a velvety microfoam finish.", 55000, "coffee", "photo-1517256064527-09c73fc73e38", true],
    ["matcha-cloud", "Matcha Cloud", "Matcha Cloud", "Matcha ceremonial êm, sữa tươi và foam vani nhẹ.", "Ceremonial matcha, fresh milk and a light vanilla cloud.", 65000, "signature", "photo-1515823662972-da6a2e4d3002", true],
    ["sunset-oolong", "Ô long hoàng hôn", "Sunset Oolong", "Ô long rang nhẹ, cam vàng và hoa nhài.", "Light-roast oolong with orange and jasmine.", 59000, "tea", "photo-1556679343-c7306c1976bc", false],
    ["rose-latte", "Rose Latte", "Rose Latte", "Sữa tươi, rose syrup nhà làm và một shot espresso.", "Fresh milk, house rose syrup and a shot of espresso.", 69000, "signature", "photo-1498804103079-a6351b050096", true],
    ["cocoa-sea-salt", "Cacao muối biển", "Sea Salt Cocoa", "Cacao đậm vị, điểm chút kem mặn thủ công.", "Deep cocoa topped with a hand-whipped sea salt cream.", 59000, "non-coffee", "photo-1542990253-a781e04c0082", false],
    ["yuzu-sparkler", "Yuzu Sparkler", "Yuzu Sparkler", "Yuzu, tonic và hương thảo cho buổi chiều tỉnh táo.", "Yuzu, tonic and rosemary for a bright afternoon.", 55000, "non-coffee", "photo-1525385133512-2f3bdd039054", false],
    ["almond-croissant", "Croissant hạnh nhân", "Almond Croissant", "Croissant bơ thơm với nhân hạnh nhân béo ngậy.", "Buttery croissant with a generous almond filling.", 55000, "pastry", "photo-1509440159596-0249088772ff", false],
    ["burnt-cheesecake", "Burnt Cheesecake", "Burnt Cheesecake", "Cheesecake nướng cháy cạnh, mềm mịn ở tâm bánh.", "Caramelised on top and impossibly creamy within.", 65000, "pastry", "photo-1551024506-0bccd828d307", true]
  ] as const;
  for (let index = 0; index < products.length; index++) { const [slug, nameVi, nameEn, descriptionVi, descriptionEn, price, category, photo, featured] = products[index]; const url = image(photo); await Product.updateOne({ slug }, { $set: { nameVi, nameEn, slug, descriptionVi, descriptionEn, price, category: categoryId(category), image: url, gallery: [url], featured, active: true, displayOrder: index + 1 } }, { upsert: true }); }
  const stories = [
    ["the-rhythm-of-slow-mornings", "Nhịp điệu của những sáng chậm", "The rhythm of slow mornings", "Có những ngày, một ly cà phê không phải để bắt đầu thật nhanh mà để bắt đầu thật đúng.", "Some days, coffee is not for starting quickly—it is for starting well.", "Một buổi sáng đẹp không cần quá nhiều điều. Một chiếc bàn có nắng, một bản nhạc vừa đủ và một ly cà phê được pha không vội. Ở 7mmcoffee, chúng tôi tin rằng nhịp chậm ấy không hề đối lập với một ngày nhiều năng lượng. Nó chỉ giúp ta nhìn rõ hơn điều mình muốn làm.\n\nVì vậy, mỗi hạt cà phê đều được chọn để có vị ngọt rõ ràng, mỗi mẻ rang được thử nhiều lần và mỗi ly được làm như thể nó là ly đầu tiên trong ngày của một người bạn.", "A beautiful morning does not ask for much. A sunlit table, music at just the right volume and coffee that is never rushed. At 7mmcoffee, we believe a slower rhythm does not take energy away from your day. It simply helps you see what matters.\n\nThat is why we choose beans for clarity and sweetness, test every roast repeatedly and make each cup as if it were a friend’s first cup of the day.", "Coffee ritual", "7mmcoffee Journal", "photo-1495474472287-4d71bcdd2085", true],
    ["why-we-rest-our-espresso", "Vì sao espresso cần thời gian nghỉ", "Why we let espresso rest", "Một vài giây nghỉ nhỏ thay đổi rất nhiều điều trong tách cà phê.", "A few quiet seconds can change an entire cup.", "Espresso vừa chiết xuất có một thế giới hương thơm rất sống động. Chúng tôi để ly nghỉ ngắn trước khi phục vụ, để vị ngọt lắng lại và cấu trúc cân bằng hơn. Đó là một thao tác nhỏ, nhưng là cách chúng tôi dành sự tôn trọng cho hạt cà phê.\n\nCà phê ngon không chỉ là công thức. Nó là sự quan sát, sự kiên nhẫn và khả năng nhận ra khi nào một điều đã vừa đủ.", "Fresh espresso has a remarkably lively aromatic world. We give it a brief pause before serving so its sweetness settles and its structure becomes more balanced. It is a small gesture, but one that respects the bean.\n\nGreat coffee is never only a recipe. It is observation, patience and knowing when something is just enough.", "Coffee knowledge", "7mmcoffee Journal", "photo-1514432324607-a09d9b4aefdd", false],
    ["a-table-for-conversation", "Một chiếc bàn cho cuộc trò chuyện", "A table for conversation", "Không gian tốt là không gian khiến bạn muốn ở lại thêm một chút.", "A good space makes you want to stay just a little longer.", "Khi thiết kế 7mmcoffee, chúng tôi bắt đầu từ câu hỏi: một cuộc trò chuyện cần gì để trở nên dễ dàng? Ánh sáng dịu, ghế ngồi thoải mái, khoảng cách vừa phải và âm nhạc không chen vào câu chuyện.\n\nKhông gian là một lời mời. Chúng tôi hy vọng lời mời ấy luôn đủ ấm để bạn quay lại cùng một người bạn, hoặc đến một mình và thấy vẫn dễ chịu.", "When we designed 7mmcoffee, we began with a question: what does a conversation need to feel easy? Gentle light, comfortable chairs, the right amount of space and music that never interrupts.\n\nA space is an invitation. We hope ours is always warm enough to return to with a friend—or to enjoy on your own.", "Our space", "7mmcoffee Journal", "photo-1518005020951-eccb494ad742", false],
    ["our-first-harvest", "Mùa hạt đầu tiên", "Our first harvest", "Một chuyến đi nhỏ để hiểu thêm về hành trình của những hạt cà phê.", "A small trip to understand the journey of every bean.", "Mỗi mùa thu hoạch đều là một lời nhắc rằng cà phê bắt đầu rất lâu trước khi chúng ta đặt tay lên tay cầm máy. Nó bắt đầu ở độ cao, đất, thời tiết và bàn tay người trồng.\n\nChúng tôi không ngừng học cách kể lại hành trình ấy bằng hương vị rõ ràng và trung thực trong mỗi ly phục vụ.", "Every harvest reminds us that coffee begins long before our hand reaches an espresso handle. It begins with altitude, soil, weather and the growers’ hands.\n\nWe keep learning how to tell that journey through flavours that feel clear and honest in every cup.", "Origin", "7mmcoffee Journal", "photo-1442512595331-e89e73853f31", false]
  ] as const;
  for (let index = 0; index < stories.length; index++) { const [slug, titleVi, titleEn, excerptVi, excerptEn, contentVi, contentEn, category, author, photo, featured] = stories[index]; await Story.updateOne({ slug }, { $set: { titleVi, titleEn, slug, excerptVi, excerptEn, contentVi, contentEn, coverImage: image(photo), category, author, publishedAt: new Date(Date.now() - index * 86400000 * 7), status: "published", featured, seoTitleVi: titleVi, seoTitleEn: titleEn, seoDescriptionVi: excerptVi, seoDescriptionEn: excerptEn } }, { upsert: true }); }
  await About.findOneAndUpdate({}, { $set: { heroTitleVi: "Cà phê, với một nhịp riêng.", heroTitleEn: "Coffee, at its own rhythm.", heroSubtitleVi: "7mmcoffee là không gian cho những cuộc gặp gỡ, khoảng lặng và các ly cà phê được pha cẩn thận.", heroSubtitleEn: "7mmcoffee is a space for meetings, quiet pauses and coffee made with care.", heroImage: image("photo-1445116572660-236099ec97a0"), storyTitleVi: "Chúng tôi tin vào những điều được làm chậm.", storyTitleEn: "We believe in things made slowly.", storyContentVi: "7mmcoffee sinh ra từ tình yêu với những chi tiết nhỏ: hạt cà phê có nguồn gốc rõ ràng, chiếc ghế đủ thoải mái để bạn ngồi lâu, và người pha chế nhớ cách bạn thích ly cà phê của mình.\n\nKhông chỉ là một quán cà phê, đây là nơi để bạn dừng lại giữa nhịp sống nhiều chuyển động—một chút, nhưng vừa đủ.", storyContentEn: "7mmcoffee began with a love for small details: traceable beans, chairs comfortable enough to linger in and baristas who remember how you enjoy your coffee.\n\nMore than a coffee shop, it is a place to pause within a moving city—just a little, but enough.", coffeeTitleVi: "Từ hạt đến khoảnh khắc", coffeeTitleEn: "From bean to moment", coffeeContentVi: "Chúng tôi tìm kiếm những hạt cà phê có vị ngọt tự nhiên và rang chúng để giữ lại nét riêng của vùng trồng. Mỗi công thức được thử lại mỗi ngày, vì một ly cà phê tử tế luôn cần sự nhất quán.", coffeeContentEn: "We seek beans with natural sweetness and roast them to preserve the character of their origin. Every recipe is tested daily because a thoughtful cup needs consistency.", philosophy: [{ titleVi: "Chất lượng", titleEn: "Quality", descriptionVi: "Đầu tư vào hạt, nước và kỹ thuật—không thỏa hiệp.", descriptionEn: "Care for beans, water and craft without compromise." }, { titleVi: "Kết nối", titleEn: "Connection", descriptionVi: "Tạo ra một nơi những cuộc trò chuyện được bắt đầu.", descriptionEn: "Make space for conversations to begin." }, { titleVi: "Sáng tạo", titleEn: "Creativity", descriptionVi: "Luôn tò mò với hương vị và những cách kể chuyện mới.", descriptionEn: "Stay curious about flavour and new ways to tell a story." }], gallery: [image("photo-1495474472287-4d71bcdd2085"), image("photo-1518005020951-eccb494ad742"), image("photo-1498804103079-a6351b050096"), image("photo-1442512595331-e89e73853f31")], cta: { labelVi: "Ghé thăm 7mmcoffee", labelEn: "Visit 7mmcoffee", href: "/contact" } } }, { upsert: true, new: true });
  await SiteSettings.findOneAndUpdate({}, { $set: { siteName: "7mmcoffee", heroImage: image("photo-1495474472287-4d71bcdd2085"), heroVideo: "", heroSloganVi: "Hơn cả cà phê, đó là một khoảnh khắc.", heroSloganEn: "More than coffee, it’s a moment.", addressVi: "27 Nguyễn Hữu Cầu, Phường Tân Định, Quận 1, TP. Hồ Chí Minh", addressEn: "27 Nguyen Huu Cau, Tan Dinh Ward, District 1, Ho Chi Minh City", phone: "+84 28 7307 7007", email: "hello@7mmcoffee.vn", openingHoursVi: "Mỗi ngày · 07:00 — 22:00", openingHoursEn: "Daily · 07:00 — 22:00", googleMapsUrl: "https://maps.google.com", facebookUrl: "https://facebook.com", instagramUrl: "https://instagram.com", tiktokUrl: "https://tiktok.com" } }, { upsert: true, new: true });
  console.log(`Seeded 7mmcoffee. Admin: ${email}`);
}

seed().catch((error: unknown) => { console.error(error); process.exitCode = 1; }).finally(async () => { await mongoose.disconnect(); });
